### ISSUE TITLE
invalid version number in `setup.py` during installation

### ISSUE THREAD

**Issue by sparthib** [LappalainenLab/lorals#11]
Hi I get this error when I try to install using setup.py 

```
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    setup(
  File "/users/sparthib/.conda/envs/isoquant/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/users/sparthib/.conda/envs/isoquant/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 146, in setup
    _setup_distribution = dist = klass(attrs)
  File "/users/sparthib/.conda/envs/isoquant/lib/python3.8/site-packages/setuptools/dist.py", line 318, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
  File "/users/sparthib/.conda/envs/isoquant/lib/python3.8/site-packages/setuptools/dist.py", line 354, in _normalize_version
    normalized = str(Version(version))
  File "/users/sparthib/.conda/envs/isoquant/lib/python3.8/site-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: ''
```

I noticed that there is no version number listed in `setup.py`

This is my conda environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
python                    3.12.4          h194c7f8_0_cpython    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

Any suggestions would be appreciated, thanks!

**Comment by sparthib** [comment]
this was solved using `venv`,  although it still gave a warning in the beginning of the installation. 
```
/users/sparthib/lorals/lorals_env/lib/python3.8/site-packages/setuptools/dist.py:477: UserWarning: The version specified ('') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
