### ISSUE TITLE
Invalid genotypes annotate_ase

### ISSUE THREAD

**Issue by illarionovaanastasia** [LappalainenLab/lorals#2]
Hi!
I am trying to run annotation of calc_ase output. The command I am using for this:
`annotate_ase -f sample.vcf.gz -i calc_ASE/sample.tsv -b gencode.bed -o annot_ase.tsv`
The run fails during a Fetching genotypes step with a following error:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/annotate_ase", line 33, in <module>
    sys.exit(load_entry_point('LORALS==0.0.0', 'console_scripts', 'annotate_ase')())
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/scripts.py", line 604, in annotate_ase
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/annotate.py", line 223, in annotate_genotypes
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/features.py", line 173, in fromvcf
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/features.py", line 193, in __init__
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/features.py", line 165, in _valid_genotype
ValueError: invalid genotypes
```
The genotype VCF was obtained with a process_vcf.sh script from a correctly formatted phased VCF.
I would really appreciate any feedback.

Best regards,

Anastasia

**Comment by Marijn-Schipper** [comment]
Hi Anastasia,

I had a similar issue. Does your VCF file contain genotypes other than 0|1, 1|0, 1|1?
1|2 for example? Removing these solved the issue for me. 
You could always temporarily reannotate 2|1 and 1|2 variants as 1|0 and 0|1, and revert this in the output.

Kind regards,
Marijn

**Comment by DafniG** [comment]
Hi both,
Sorry for the delay in responding. Thank you Marjin for the suggestion. Could you confirm Anastasia whether the problem was fixed by changing the genotypes? If so, I can updated both the process_vcf.sh script and I will update the instructions to reflect it. 
Thank you,
Dafni

**Comment by illarionovaanastasia** [comment]
Hi both,

Thank you for the responses. I also have figured out that the issue is in the unexpected format of genotypes in the input VCF and edited the script. I confirm that it solved the problem.
Thank you!

Best regards,

Anastasia
