### ISSUE TITLE
An issue with installation in conda environment

### ISSUE THREAD

**Issue by alanlamsiu** [LappalainenLab/lorals#3]
Hi~ I was trying to set up a conda environment solely for LORALS. I first set up a conda environment, and modified the $PATH and $PYTHONPATH to inlcude the directories in the conda environment. Then I use the `python setup.py install --prefix=/path/to/conda/environment` to install LORALS. After that, I ran `calc_ase --help`. But the following error messages showed up. It would be great if you can give any suggestions on the issue.

Thansk!

Best,
Xiao

"Traceback (most recent call last):
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/site-packages/LORALS-0.0.0-py3.9.egg/lorals/__init__.py", line 4, in <module>
NameError: name '__LORALS_SETUP__' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/bin/calc_ase", line 33, in <module>
    sys.exit(load_entry_point('LORALS==0.0.0', 'console_scripts', 'calc_ase')())
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/bin/calc_ase", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/site-packages/LORALS-0.0.0-py3.9.egg/lorals/__init__.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/site-packages/LORALS-0.0.0-py3.9.egg/lorals/asts.py", line 15, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/lib/python3.9/site-packages/LORALS-0.0.0-py3.9.egg/lorals/features.py", line 8, in <module>
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/sc/arion/work/linx19/utilities/miniconda3/py38_4.9.2/envs/lorals/bin/python"
  * The NumPy version is: "1.21.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
"

**Comment by alanlamsiu** [comment]
The issue was solved by unsetting some environmental variables as below.

`unset PYTHONPATH`
`unset PERL5LIB`
`unset R_LIBS`
