### ISSUE TITLE
ValueError: invalid genotypes in calc_asts -m quant

### ISSUE THREAD

**Issue by yyaal** [LappalainenLab/lorals#5]
hello, I have try to use lorals to analysis my data . but I meet error when I ues command calc_asts 。
Here is my commond 
calc_asts -m quant -b /mnt/raid66/Personal_data/zhangdan/MIA/00_data_ingest/26_WGS/09.ont-RNA.lorals/01.test2_testis/01.minimap2/bk_ontcDNA_C57_F_m2_testis.sam2w.gemo.aln.bam -i /mnt/raid66/Personal_data/zhangdan/MIA/00_data_ingest/26_WGS/09.ont-RNA.lorals/01.test2_testis/05.annotate_ase/bk_ontcDNA_C57_F_m2_testis.sam2w.gemo.annotate_ase.tsv -o /mnt/raid66/Personal_data/zhangdan/MIA/00_data_ingest/26_WGS/09.ont-RNA.lorals/01.test2_testis/06.calc_asts/bk_ontcDNA_C57_F_m2_testis.sam2w.gemo.calc_asts.tsv -x /mnt/raid66/Personal_data/zhangdan/MIA/00_data_ingest/26_WGS/09.ont-RNA.lorals/01.test2_testis/01.minimap2/bk_ontcDNA_C57_F_m2_testis.sam2w.cdna.aln.bam -w 8 -t 20

The error is 
2022-10-14 16:37:57 INFO:       Welcome to calc_asts !
2022-10-14 16:37:57 INFO:       Author: Dafni Glinos (dglinos@nygenome.org)
Traceback (most recent call last):
  File "/mnt/data4/wanghuanhuan/conda/conda_data/miniconda3/envs/lorals/bin/calc_asts", line 33, in <module>
    sys.exit(load_entry_point('LORALS==0.0.0', 'console_scripts', 'calc_asts')())
  File "/mnt/data4/wanghuanhuan/conda/conda_data/miniconda3/envs/lorals/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/scripts.py", line 371, in calc_asts
  File "/mnt/data4/wanghuanhuan/conda/conda_data/miniconda3/envs/lorals/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/scripts.py", line 125, in _read_ase
  File "/mnt/data4/wanghuanhuan/conda/conda_data/miniconda3/envs/lorals/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/features.py", line 202, in geno
  File "/mnt/data4/wanghuanhuan/conda/conda_data/miniconda3/envs/lorals/lib/python3.8/site-packages/LORALS-0.0.0-py3.8.egg/lorals/features.py", line 165, in _valid_genotype
ValueError: invalid genotypes
I have learn the issues 2 .
https://github.com/LappalainenLab/lorals/issues/2
and I am sure my reference vcf file on contains  0|1, 1|0, 1|1 in genotypes 
also I check out my bk_ontcDNA_C57_F_m2_testis.sam2w.gemo.annotate_ase.tsv .
I find the GENOTYPE in the .annotate_ase.tsv is only contains "NaN" , is that what caused the error ？
I don't know how to solve this problem and I've had this problem many times 。
I would really appreciate any feedback.

Best regards,

mally

**Comment by haowBio** [comment]
I meet the same problem, have you solved it?

**Comment by DafniG** [comment]
Hi @yyaal and @haowBio,

Could one of you share a few lines of your *.annotate_ase.tsv file?

The --genotype filter is optional so it should not have an impact on running calc_asts but you could try fill this column with 0 and see whether that helps.
