### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by H-Qiya** [LappalainenLab/lorals#8]
Hi,
I was trying to run LORALS, but it seemed that I fell into a dead loop.
First I created an independent environment named LORALS in conda, installed samtools as well as bedtools, and ran the code: 

> python3 setup.py install

It then reported an error:

> Traceback (most recent call last): 
> File "setup.py", line 18, in <module>
> from setuptools import setup
> ModuleNotFoundError: No module named 'setuptools'

So I installed pip and used pip to install setuotools successfully, and ran the code again:

> python3 setup.py install

This time it reported:

> Traceback (most recent call last):
> File "setup.py", line 82, in <module>
>  import lorals.scripts as scripts
> ModuleNotFoundError: No module named 'lorals'

I wondered that, if the statement "LORALS depends on Python 3, SAMTools, and Bedtools. All other dependencies are installed automatically by pip" is true, why I need to install 'lorals' before running setup.py? Is it a dead loop?
I search again and found this page: 

[https://lappalainenlab.github.io/lorals/index.html](url)

![image](https://github.com/LappalainenLab/lorals/assets/75819078/4331ec07-59aa-4238-ade6-313b38047a5d)

And I ran the code from it:

> pip install git+https://github.com/mojaveazure/lorals.git

Still failed. Then I suddenly noticed that the website might be outdated, and I changed to the following command:

> pip install git+https://github.com/LappalainenLab/lorals.git

Failed again :(

Could you please help me with this installation problem? Looking forward to your reply!

**Comment by NikoLichi** [comment]
Hi there,

I am just another user using LORALS and did the same installation as you. Perhaps you solved this issue already but just in case.
As a suggestion, if you use conda dependencies try to install dependencies from Anaconda. I the past, I had trouble mixing pip and conda dependencies. I suggest you install setuptools from anaconda like:
`conda install -c conda-forge setuptools`

In my case, conda complained about a g++ and gcc dependencies which I installed using conda. And it seems to be working "fine".

I hope this helps, 

All the best,
Niko

**Comment by bkcenik** [comment]
I'm also just a user - I had similar compiling issues when I was trying to install (on an HPC environment). Using an up to date version of gcc fixed my problem. Our default version is 4.x, I just loaded 11.2.0 and was able to install without issues.
